version: 2

jobs:
  test:
    docker:
      - image: circleci/node:11.3.0
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - /root/.npm

      - run:
          name: Run tests
          command: npm test
  release:
    docker:
      - image: circleci/node:11.3.0
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - /root/.npm

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

      - run:
          name: Build
          command: npm run build

      - run:
          name: Publish package
          command: npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - release:
          context: pus
          requires:
            - test
